### ISSUE TITLE
Support NETStandard

### ISSUE THREAD

**Issue by skarllot** [jam40jeff/ITask#2]
Add support for NETStandard platform.

**Comment by mculhane1** [comment]
Here is a PR that transitions the project onto .NETStandard2.0

https://github.com/jam40jeff/ITask/pull/12

**Comment by jam40jeff** [comment]
The library will be updated to support netstandard1.0 as part of this pull request.

**Comment by jam40jeff** [comment]
This is available as of the MorseCode.ITask 2.0.0 package that was just published to NuGet.
