### ISSUE TITLE
Add GetAwaiter() to ease consumption?

### ISSUE THREAD

**Issue by binki** [jam40jeff/ITask#4]
In the docs I see:

> Note that the functionality required by the compiler to enable `await` keyword support is included in a class in the `MorseCode.ITask` namespace.  Therefore, a `using` statement will need to be added to the file for this code to compile as follows:
>
> ```c#
> using MorseCode.ITask;
> ```

I think that if `GetAwaiter()` were added to the `ITask` and `ITask<TResult>` interfaces, this would be unnecessary. I haven’t actually tested that, though.

This would be a breaking change for anyone trying to implement `ITask` or `ITask<TResult>`. The cleanest way to avoid issues with the break might be to rename the nuget package itself to something like `MorseCode.ITask2`.

**Comment by jam40jeff** [comment]
Thanks.  I will look into this but I can't think of a reason not to do this.

**Comment by binki** [comment]
I was planning to make a PR with this to experiment and verify it.

The main reason not to do it is from an ABI perspective: if people ever implemented `ITask` themselves, their implementations will all start failing to compile if updating to a new version of `MorseCode.ITask` NuGet.

Another reason not to do this might be whatever reason you had to make `GetAwaiter` an extension method in the first place. Was there a reason for that design? Maybe to try to reduce the number of members in the interface to be as few as possible? Maybe you remember ;-).
